#!/usr/bin/env -S docker stack deploy --with-registry-auth datasets -c

version: "3.9"

# NOTE deploy
# docker stack deploy --with-registry-auth -c docker-stack.yaml datasets

services:
  datasets:
    image: softvisio/datasets
    init: true
    stop_grace_period: 5m

    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1

    environment:
      APP_MAXMIND_LICENSE_KEY:
      APP_GITHUB_TOKEN:

    networks: [private]

    volumes:
      - { type: tmpfs, target: /dev/shm, tmpfs: { size: 1073741824 } }
      - { type: volume, source: datasets, target: /var/lib/docker/volumes/datasets/_data }

    build:
      context: .

networks:
  private: { external: true }

volumes:
  datasets: { name: datasets }

x-build:
  default_tag: latest
  # autobuild_tags: [main, devel, latest]
