#!/usr/bin/env -S docker stack deploy --with-registry-auth maxmind -c

version: "3.9"

# NOTE deploy
# docker stack deploy --with-registry-auth -c docker-stack.yaml maxmind

services:
  maxmind:
    image: softvisio/maxmind

    deploy:
      mode: global

    environment:
      MAXMIND_LICENSE_KEY:

    networks: [private]

    volumes:
      - { type: volume, source: maxmind, target: /var/lib/maxmind }

    init: true
    stop_grace_period: 5m
    shm_size: 1g

    build:
      context: .

networks:
  private: { external: true }

volumes:
  maxmind: { name: "maxmind" }

x-build:
  default_tag: latest
  # auto_tags: [main, devel, latest]
  # tags_mapping: { main: latest }
