name: Build datasets
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *" # every day at 12:00
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: softvisio/datasets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MAXMIND_LICENSE_KEY: ${{ secrets.MAXMIND_LICENSE_KEY }}
    steps:
      - run: |
          . /etc/profile.d/n.sh
          export DATASETS_DOWNLOAD=false
          npm i --no-fund --no-audit
          bin/update.js --build --force
        shell: bash
        working-directory: /var/local/package
