name: build resources
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *" # every day at 12:00
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zerocluster/datasets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: |
          export DOWNLOAD_EXTERNAL_RESOURCES=false
          NODE_ENV= npm i
          npm run build
        shell: bash
        working-directory: /var/local/package
